spring.application.name=SpringJDBCEx
spring.datasource.url=jdbc:postgresql://localhost:5433/akash
spring.datasource.username=postgres
spring.datasource.password=yourpass
spring.datasource.driver-class-name=org.postgresql.Driver